# -*- coding: utf-8 -*-
"""Untitled105.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyGnYN67OqODSx51QILJh6Gp8o2VvSxI
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data = pd.read_csv('/data/iris.csv')

data.head()

X = data.drop('species', axis=1)
y = data['species']

model = DecisionTreeClassifier(random_state=42)

model.train(X, y)

predictions = model.predict(X)

accuracy = accuracy_score(y, predictions)
print('Accuracy:', accuracy)
